"""renamed_user_table_column

Revision ID: f3d5c558a20e
Revises: 31bdaf73bf1c
Create Date: 2024-05-11 21:58:48.075687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d5c558a20e'
down_revision: Union[str, None] = '31bdaf73bf1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'email_confirmed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmed', sa.BOOLEAN(), nullable=False))
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
